language: node_js
node_js:
    - 12
deploy:
  provider: heroku
  api_key:
    secure: r9rQmiJmDKujqiCzwhQITtNKmFqg1DRgDUccKtqa6ONcj7kA1I0kIGvqOB7i8gaEArJ4bXHrHODeKswEDynpx2E5rzGP3wpMxR+m171j7ZCvxv455oQirHIdLBJgUrqcnA+McDZG8xXyEk5pi+ClEbMj/k+De2Rtbpu6vzkB92qskH0QURWSCCWmlOBit6rBuhTPq+7ynzrOzjSyDstrz4OOsSynJGfv+iLpExRWXDWE6gICbSvvrcmf2weHZ75jtIFAR9s2ZMTTjjgjAF1UVOnNkL8OpxqPEgNqd96q8hns38gUioXdKsqia6CjAlSw96vuYSX0ohKSGomVi+/NdEcy3wiro2YxV6tygtL5yTeu54cDO+pIx32Gegqr96GxnNIICnTdgSmVrv9BqStsUEmxHNqbm87PZg7jE0MWM8LaI/c10HMDyQC5xtSM1pp0e0rG2J158hMq3BCVFC7P548V824Jh3aFPgPKKoNxjjjonQPNGKZ1/cGsJkSFjvOH4tlI6mrvMWyelyxfx9Qu/gKV4f4/DdhKxfaC8XaMHwoGPHtWE63kle7BzoyJGWmTfKNvPusjjGEeZ9ssGG9k5OCSTuJxMUSRwznnrqQ1RB5m/6Jynne56ByMdsShy2M0HreF4o6mHuv+DmuO5oUaQj2eQlesz95mp/wFLt5ALFM=
  app: sveza
