language: node_js
node_js:
- 12
deploy:
  provider: heroku
  api_key:
    secure: tL6Hqg3ArK4SXAe/xvNP04VLAtO/rhuBG1JyTuttuwv6SZ+YAZ77xAsOKiAHoBPRKTwMSwn9nHHcw2cckXOgRG3u2nlTzI5IWJqjzSU2M56hI0tpH+TjXzgwT79rxGtJ6r5tPzx08hqms5UDYcN5LKYvwyuY6vzZY8mWROpbJolKOAk1tEFB9SkgJJpQ+coLuhhKs2AKJo5xON6BDbT/KFBUOOsnWFjm33/F0bRsP1NP4CcAeK4vOmGWYbERO2WkfsT4jeZzogOWqBUoq9jCPxzIGQE9uyKS4WodWoHjNE2C+A3GZZJWaKg1mdfLuT2M+GFRdunth9FjlbTU/FEFfShbkEHPh8OihWz/xFXAGA9v3wpeey9IFMmYkxgQotz+llHdYIqQxYQ74kzAgv1B8trh72+SkYyWsgeP4N3X6dnYJpFtnBSOVtwuYZPeYDxPxW3iCg6wSPt74dmef4PTugCDZC/vt4GFW2sJigaeZjksfqMs6D7gFYnvyMJT6CUS0zy6V/O3865IdBJ7xPjM6MGig2DqcGuiBdxZSRgSf+i0JXsgCrQMflNVpv1m04tooalhMrDTlsm5nt6S+MdP7er79HMHgZSE1mV5oNolcOHn3fD50xD23JadKB5bX1TjDOhFc7cJnsanye8rTiuhWd844n1cloBe/9tUsknfTlM=
  app: sveza
