language: node_js
node_js:
- 12
deploy:
  provider: heroku
  api_key:
    secure: Er7OR+lIf58Cp3JwcKe7lacKYCUO36Q6ahNMETe54IWxKckJMReKkXeKw/0fnInG2JpjZg5YUIvnstGrCR2tkRL8dRoCoRYOgU6jS7xkeSb6kCeEocYqbmPbzMIIzWzkwLuEjVHMW9IfKK3AlYqmLZE4ESuDtsP26nBYhENy3eqW8nS2H5hCzTadCsPfQ7oXT0uMhlz0a0DJ26EjEypBjCZjxb6WykjJDhFXbMiUEoXHhWQQsJaiJ7dPYCz+raZxAeDg/dMV4NBRXxwX5FZIsVKxThOgwnXumBAQO5UMrPA1eiaU3euTSccbGkwfXCWbSuzydD7YiywbDOSe6u1HPQpe3/cqUCgsoQ6XmlK3KEzm+Ja6c6KGtjGQtc4krycufBmiBuXxdLPCH641KTDxuSs0/SAsSg4zGjFgzNW0GxvVXxXN7M5u26G5UaEDWnJ/YNsKJYXfZP7ONfH8KhSlgCGtrFf/cu2PdU5Av618xyoGXhWMGYMVFGVGwt28FmIaMS9TuKGpmr0MjrMLtLmqRP5nYleo8ynbvakVoBhpZRT9fTamKKxzTaf7WuwDJ9gYltM5MdyohrVSVCMoqxeqxnsevZYFVXJbeIrWztYmNwHM5qMitlu9rXTzYpvPypKv/Pq4cVS8bTJOPu9AVoTsE70Zhpeh6+4XmegV6ueXkY0=
  app: sveza
